name: Build, Push Docker Images, and Create Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - base_image: alpine:latest
            image_name: alpine
          - base_image: ubuntu:latest
            image_name: ubuntu
          - base_image: debian:latest
            image_name: debian
          - base_image: centos:latest
            image_name: centos
          - base_image: fedora:latest
            image_name: fedora
          - base_image: busybox:latest
            image_name: busybox
          - base_image: node:latest
            image_name: node
          - base_image: python:latest
            image_name: python
          - base_image: openjdk:latest
            image_name: openjdk
          - base_image: golang:latest
            image_name: golang
          - base_image: nginx:latest
            image_name: nginx
          - base_image: redis:latest
            image_name: redis
          - base_image: mysql:latest
            image_name: mysql
          - base_image: postgres:latest
            image_name: postgres
          - base_image: mongo:latest
            image_name: mongo
          - base_image: php:latest
            image_name: php
          - base_image: ruby:latest
            image_name: ruby
          - base_image: rust:latest
            image_name: rust
          - base_image: elixir:latest
            image_name: elixir
          - base_image: mcr.microsoft.com/dotnet/runtime:latest
            image_name: dotnet-runtime
          - base_image: amazoncorretto:latest
            image_name: amazoncorretto
          - base_image: oraclelinux:latest
            image_name: oraclelinux
          - base_image: tensorflow/tensorflow:latest
            image_name: tensorflow
          - base_image: eclipse-temurin:latest
            image_name: eclipse-temurin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        env:
          IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/base-${{ matrix.image_name }}:latest
        run: |
          docker build --file Dockerfile --build-arg BASE_IMAGE=${{ matrix.base_image }} -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}-${{ matrix.image_name }}
          release_name: Release ${{ matrix.image_name }} v${{ github.run_number }}
          body: |
            Release of ${{ matrix.image_name }} Docker image.
          token: ${{ secrets.GITHUB_TOKEN }}
