name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - base_image: alpine:latest
            image_name: alpine
          - base_image: ubuntu:latest
            image_name: ubuntu
          - base_image: debian:latest
            image_name: debian
          - base_image: centos:latest
            image_name: centos
          - base_image: fedora:latest
            image_name: fedora
          - base_image: busybox:latest
            image_name: busybox
          - base_image: node:latest
            image_name: node
          - base_image: python:latest
            image_name: python
          - base_image: openjdk:latest
            image_name: openjdk
          - base_image: golang:latest
            image_name: golang
          - base_image: nginx:latest
            image_name: nginx
          - base_image: redis:latest
            image_name: redis
          - base_image: mysql:latest
            image_name: mysql
          - base_image: postgres:latest
            image_name: postgres
          - base_image: mongo:latest
            image_name: mongo
          - base_image: php:latest
            image_name: php
          - base_image: ruby:latest
            image_name: ruby
          - base_image: rust:latest
            image_name: rust

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image - ${{ matrix.image_name }}
        run: |
          docker build --file Dockerfile --build-arg BASE_IMAGE=${{ matrix.base_image }} -t ${{ secrets.DOCKER_USERNAME }}/base-${{ matrix.image_name }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/base-${{ matrix.image_name }}:latest
